os:
  - linux
services:
  - docker
install:
  - docker build -t morehai/platform-registry:travis .
  - docker run --name platform-registry -p 8761:8761 -d -t morehai/platform-registry:travis
script:
  - sleep 30
  - docker ps
  - docker logs platform-registry
